# Generated by Django 5.1.6 on 2025-03-21 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Martiapp', '0002_post_autor_alter_post_contenido'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='estado',
            field=models.CharField(choices=[('B', 'Borrador'), ('P', 'Publicado')], default='B', max_length=1),
        ),
    ]
